#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
  ifeq ($(GNUSTEP_MAKEFILES),)
    $(warning )
    $(warning Unable to obtain GNUSTEP_MAKEFILES setting from gnustep-config!)
    $(warning Perhaps gnustep-make is not properly installed,)
    $(warning so gnustep-config is not in your PATH.)
    $(warning )
    $(warning Your PATH is currently $(PATH))
    $(warning )
  endif
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Framework
#
VERSION = 0.1
PACKAGE_NAME = WebKit
FRAMEWORK_NAME = WebKit
WebKit_CURRENT_VERSION_NAME = 0.1
WebKit_DEPLOY_WITH_CURRENT_VERSION = yes


#
# Public headers (will be installed)
#
WebKit_HEADER_FILES = \
WebKit.h \
WebView.h

#
# Objective-C Class files
#
WebKit_OBJC_FILES = \
WebView.mm

#
# AutoGSDoc
#
DOCUMENT_NAME = WebKit

WebKit_AGSDOC_FILES = WebKit.gsdoc \
	$(WebKit_HEADER_FILES) \
	$(WebKit_OBJC_FILES) \


WebKit_AGSDOC_FLAGS += -MakeFrames YES


#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/framework.make
-include GNUmakefile.postamble
-include GNUmakefile.generated


#Only build documentation if doc=yes was passed on the command line
#
ifeq ($(doc),yes)
include $(GNUSTEP_MAKEFILES)/documentation.make
endif
